var kiosk = kiosk || {};
(function () {
    kiosk.enum = kiosk.enum || {};
    kiosk.enum.WorkType = {
        SendRequest: 1,
        PostRequest: 2,
        ResetDevice: 3,
        ResetConnection: 4
    };
    kiosk.enum.ScannerAction = {
        Close: 0,
        Open: 1,
        Reset: 3,
        ScanningBarCode: 4,
        ScanningBitMap: 5
    };
    kiosk.enum.ThermalAction = {
        Open: 1,
        Reset: 2,
        CutPaper: 3,
        Close: 4,
        PrintText: 5,
        PrintBitmap: 6,
        PrintBarCode: 7,
        PrintQRCode: 8,
        CheckNearEnd: 9,
        GetReviceStatus: 10,
        TransactionPrint: 11,
        Rotation: 12,
        PrintTemplatePage: 13
    };
    kiosk.enum.culture = {
        'ENUS': 1,
        'ZHTW': 2,
        'ZHCH': 13,
        'JAJP': 3,
        'KOKR': 4,
        '555': 5,
        '666': 6,
        '777': 7,
        '888': 8,
        '999': 9,
        '000': 10,
    };
    returnCulture = {
        1: "en",
        2: "zh_TW",
        13:'zh_CN',
        3: "jp",
        4: "ko",
        5: "555",
        6: "666",
        7: "777",
        8: "888",
        9: "999",
        10: "000",
    };
    kiosk.wording = {
        //英文
        1: {
            mainMenu: {
                mainMenuTitle1: "欢迎使用自助退税服务，请选择语言",
                mainMenuTitle2: "Welcome to Tax Refund Application Kiosk.",
                mainMenuTitle3: "Please select language to start",
                lang01: '繁體中文',
                lang13: '简体中文',
                lang02: 'English',
                lang03: '日本語',
                lang04: '한국어',
                lang05: 'ไทย',
                lang06: 'हिन्दी',
                lang07: 'Español',
                lang08: 'Le français',
                lang09: 'русский',
                lang10: 'Tiếng việt',
            },
            remind: {
                remindTitle1: 'en提醒您',
                remindTitle2: 'en離開退稅機前務必取得退稅表單',
                remindTitle3: 'en請準備好您的護照/入臺證、購物發票開始辦理退稅',
                btTitle: '確認，開始退稅',
                toSelectDoc: 'selectDoc',
            },
            selectDoc: {
                selectTitle: 'Select your ID document used to enter Taiwan during this trip',
                passport: 'Passport',
                permit: 'Exit & Entry Permit',
                toScanPassport: 'scanPassport',
                toScanPermit: 'scanPermit',
            },
            scanPassport: {
                scanPassportTitle: 'Please scan your passport',
                scanError: 'Scan error, please try again',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
            },
            scanPermit: {
                scanPermitTitle: 'Please scan your permit',
                scanError: 'Scan error, please try again',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
            },
            error: {
                errorTitle: 'en請攜帶您的身分資料及發票至服務中心101號櫃台，',
                errorTitle2: 'en將有專人為您服務，謝謝',
                toHomeText: 'en回服務首頁',
            },
            preScanQRcode: {
                preScanQRcodeTitle: 'Prepare to scan QR Code within your invoices',
                btScanQRcode: 'Start scan',
                toScanQR: 'scanQRcode',
            },
            scanQRcode: {
                scanQRcodeTitle1: 'Please scan QR Code within your invoices',

                scanQRcodeTitle2: '您今日已辦理退稅',
                scanQRcodeTitle4: '元',

                scanQRcodeTitle5: '發票掃描',
                scanQRcodeTitle6: '消費金額',
                scanQRcodeTitle7: '退稅淨額',

                scanQRcodeTitle8: '張',
                scanQRcodeTitle9: '新台幣',
                scanQRcodeTitle10: '新台幣',

                scanQRcodeTitle14: '詳細資訊',
                scanQRcodeTitle15: '確認',

                scanQRError1: 'en非本日發票無法申請退稅，',
                scanQRError2: 'en請掃描下一張發票',
                toDetail: 'detail',
                toSign: 'sign',
            },
            detail: {
                detailTitle1: 'You have scanned below invoices',
                detailTitle2: '上下滑動看更多',
                detailTitle3: 'en發票號碼：',
                detailTitle4: 'en品名/型號：',
                detailTitle5: 'en單價/數量：',
                detailTitle6: 'en含稅金額：',
                btDetail1: '確認，回上一頁',
                btDetail2: '刪除',
                toScanQR: 'scanQRcode',
            },
            sign: {
                signTitle1: 'Please sign in the below space',
                signTitle2: ' sec.',
                btSign1: '清除簽名',
                btSign2: '確認簽名',
                toSuccess: 'success',
            },
            success: {
                successTitle1: 'en申請成功，明細表列印中，請稍後！',
                successTitle2: 'en小額退稅者請持明細表至服務櫃檯領取退稅款現金。',
                successTitle3: 'en大額退稅請至出境機場/港口領取您的退稅款，',
                successTitle4: 'en或洽101館內市區特約退稅櫃檯。',
                toHomeText: 'en服務首頁',
            },
        },

        // 繁體中文
        2: {
            common: {
                indexPage: '首頁',
                prePage: '上一頁'
            },
            mainMenu: {
                mainMenuTitle1: "歡迎使用自助退稅服務，請選擇語言",
                mainMenuTitle2: "Welcome to tax refund self-service kiosk.",
                mainMenuTitle3: "Please select language",
                lang01: '繁體中文',
                lang13: '简体中文',
                lang02: 'English',
                lang03: '日本語',
                lang04: '한국어',
                lang05: 'ไทย',
                lang06: 'हिन्दी',
                lang07: 'Español',
                lang08: 'Le français',
                lang09: 'русский',
                lang10: 'Tiếng việt',
            },
            remind: {
                remindTitle1: '提醒您',
                remindTitle2: '離開退稅機前務必取得退稅表單',
                remindTitle3: '請準備好您的護照/入臺證、購物發票開始辦理退稅',
                btTitle: '確認，開始退稅',
                toSelectDoc: 'selectDoc'
            },
            selectDoc: {
                selectTitle: '請選擇本次入境臺灣所使用證照',
                passport: '護照',
                permit: '入出境許可證',
                toScanPassport: 'scanPassport',
                toScanPermit: 'scanPermit'
            },
            scanPassport: {
                scanPassportTitle: '請掃描您的護照',
                scanError: '掃描錯誤，請重新操作',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
                scanPassportLoading: '護照掃描中<div id="circleG"><div id="circleG_1" class="circleG"></div><div id="circleG_2" class="circleG"></div><div id="circleG_3" class="circleG"></div></div>',
                passportCerting:'資料驗證中<div id="circleG"><div id="circleG_1" class="circleG"></div><div id="circleG_2" class="circleG"></div><div id="circleG_3" class="circleG"></div></div>',
                passportCerted:'<div style="margin-top: 10px;">驗證成功</div>'
            },
            scanPermit: {
                scanPermitTitle: '請掃描您的入臺證條碼',
                scanError: '掃描錯誤，請重新操作',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
                putPermit:'請放置入臺證',
                permitCerting: '資料驗證中<div id="circleG"><div id="circleG_1" class="circleG"></div><div id="circleG_2" class="circleG"></div><div id="circleG_3" class="circleG"></div></div>',
                permitCerted: '<div style="margin-top: 10px;">驗證成功</div>'
            },
            error: {
                errorTitle: '請攜帶您的身分資料及發票至服務中心101號櫃台，',
                errorTitle2: '將有專人為您服務，謝謝',
                toHomeText: '回服務首頁',
            },
            preScanQRcode: {
                preScanQRcodeTitle: '準備掃描購物發票QR Code',
                btScanQRcode: '開始掃描',
                toScanQR: 'scanQRcode',
            },
            scanQRcode: {
                scanQRcodeTitle1: '請掃描您的購物發票',

                scanQRcodeTitle2: '您今日已辦理退稅',
                scanQRcodeTitle4: '元',

                scanQRcodeTitle5: '發票掃描',
                scanQRcodeTitle6: '消費金額',
                scanQRcodeTitle7: '退稅淨額',

                scanQRcodeTitle8: '張',
                scanQRcodeTitle9: '新台幣',
                scanQRcodeTitle10: '新台幣',

                scanQRcodeTitle14: '詳細資訊',
                scanQRcodeTitle15: '確認',

                scanQRError1: '非本日發票無法申請退稅，<br>請掃描下一張發票',
                scanQRError2: '請掃描下一張發票',
                scanQRErrorDup:'發票重複輸入，<br>請掃描下一張發票',
                scanQRcodeLoading: '資料查詢中<div id="circleG"><div id="circleG_1" class="circleG"></div><div id="circleG_2" class="circleG"></div><div id="circleG_3" class="circleG"></div></div>',
                toDetail: 'detail',
                toSign: 'sign',                
            },
            detail: {
                detailTitle1: '您已輸入的購物發票',
                detailTitle2: '上下滑動看更多',
                detailTitle3: '發票號碼：',
                detailTitle4: '品名/型號：',
                detailTitle5: '單價/數量：',
                detailTitle6: '含稅金額：',
                btDetail1: '確認，回上一頁',
                btDetail2: '刪除',
                toScanQR: 'scanQRcode',
            },
            sign: {
                signTitle1: '請於下方欄位簽名',
                signTitle2: ' 秒',
                btSign1: '清除簽名',
                btSign2: '確認簽名',
                toSuccess: 'success',
            },
            success: {
                successTitle1: '申請成功，明細表列印中，請稍後！',
                successTitle2: '小額退稅者請持明細表至服務櫃檯領取退稅款現金。',
                successTitle3: '大額退稅請至出境機場/港口領取您的退稅款，',
                successTitle4: '或洽101館內市區特約退稅櫃檯。',
                toHomeText: '服務首頁',
            },
        },
        // 簡體中文
        13: {
            mainMenu: {
                mainMenuTitle1: "欢迎使用自助退税服务，请选择语言",
                mainMenuTitle2: "Welcome to tax refund self-service kiosk.",
                mainMenuTitle3: "Please select language",
                lang01: '繁體中文',
                lang13: '简体中文',
                lang02: 'English',
                lang03: '日本語',
                lang04: '한국어',
                lang05: 'ไทย',
                lang06: 'हिन्दी',
                lang07: 'Español',
                lang08: 'Le français',
                lang09: 'русский',
                lang10: 'Tiếng việt',
            },
            remind: {
                remindTitle1: '提醒您',
                remindTitle2: '离开退税机前请务必取得退税表单',
                remindTitle3: '请准备好您的正本入境文件(护照/入台证)及购物发票开始办理退税',
                btTitle: '确认，开始退税',
                toSelectDoc: 'selectDoc',
                indexPage:'首页',
                prePage:'上一页'
            },
            selectDoc: {
                selectTitle: '請選擇本次入境臺灣所使用證照',
                passport: '護照',
                permit: '入出境許可證',
                toScanPassport: 'scanPassport',
                toScanPermit: 'scanPermit',
                indexPage: '首页',
                prePage: '上一页'
            },
            scanPassport: {
                scanPassportTitle: '請掃描您的護照',
                scanError: '掃描錯誤，請重新操作',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
                scanPassportLoading: '護照掃描中<div id="circleG"><div id="circleG_1" class="circleG"></div><div id="circleG_2" class="circleG"></div><div id="circleG_3" class="circleG"></div></div>',
                passportCerting: '資料驗證中<div id="circleG"><div id="circleG_1" class="circleG"></div><div id="circleG_2" class="circleG"></div><div id="circleG_3" class="circleG"></div></div>',
                passportCerted: '<div style="margin-top: 10px;">驗證成功</div>'
            },
            scanPermit: {
                scanPermitTitle: '請掃描您的入臺證條碼',
                scanError: '掃描錯誤，請重新操作',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
                putPermit: '請放置入臺證',
                permitCerting: '資料驗證中<div id="circleG"><div id="circleG_1" class="circleG"></div><div id="circleG_2" class="circleG"></div><div id="circleG_3" class="circleG"></div></div>',
                permitCerted: '<div style="margin-top: 10px;">驗證成功</div>'
            },
            error: {
                errorTitle: '請攜帶您的身分資料及發票至服務中心101號櫃台，',
                errorTitle2: '將有專人為您服務，謝謝',
                toHomeText: '回服務首頁',
            },
            preScanQRcode: {
                preScanQRcodeTitle: '準備掃描購物發票QR Code',
                btScanQRcode: '開始掃描',
                toScanQR: 'scanQRcode',
            },
            scanQRcode: {
                scanQRcodeTitle1: '請掃描您的購物發票',

                scanQRcodeTitle2: '您今日已辦理退稅',
                scanQRcodeTitle4: '元',

                scanQRcodeTitle5: '發票掃描',
                scanQRcodeTitle6: '消費金額',
                scanQRcodeTitle7: '退稅淨額',

                scanQRcodeTitle8: '張',
                scanQRcodeTitle9: '新台幣',
                scanQRcodeTitle10: '新台幣',

                scanQRcodeTitle14: '詳細資訊',
                scanQRcodeTitle15: '確認',

                scanQRError1: '非本日發票無法申請退稅，<br>請掃描下一張發票',
                scanQRError2: '請掃描下一張發票',
                scanQRErrorDup: '發票重複輸入，<br>請掃描下一張發票',
                scanQRcodeLoading: '資料查詢中<div id="circleG"><div id="circleG_1" class="circleG"></div><div id="circleG_2" class="circleG"></div><div id="circleG_3" class="circleG"></div></div>',
                toDetail: 'detail',
                toSign: 'sign',
            },
            detail: {
                detailTitle1: '您已輸入的購物發票',
                detailTitle2: '上下滑動看更多',
                detailTitle3: '發票號碼：',
                detailTitle4: '品名/型號：',
                detailTitle5: '單價/數量：',
                detailTitle6: '含稅金額：',
                btDetail1: '確認，回上一頁',
                btDetail2: '刪除',
                toScanQR: 'scanQRcode',
            },
            sign: {
                signTitle1: '請於下方欄位簽名',
                signTitle2: ' 秒',
                btSign1: '清除簽名',
                btSign2: '確認簽名',
                toSuccess: 'success',
            },
            success: {
                successTitle1: '申請成功，明細表列印中，請稍後！',
                successTitle2: '小額退稅者請持明細表至服務櫃檯領取退稅款現金。',
                successTitle3: '大額退稅請至出境機場/港口領取您的退稅款，',
                successTitle4: '或洽101館內市區特約退稅櫃檯。',
                toHomeText: '服務首頁',
            },
        },

        //日文
        3: {
            mainMenu: {
                mainMenuTitle1: "歡迎使用自助退稅服務，請選擇語言",
                mainMenuTitle2: "Welcome to tax refund self-service kiosk.",
                mainMenuTitle3: "Please select language",

                lang01: '中文',
                lang02: 'English',
                lang03: '日本語',
                lang04: '한국어',
                lang05: 'ไทย',
                lang06: 'हिन्दी',
                lang07: 'Español',
                lang08: 'Le français',
                lang09: 'русский',
                lang10: 'Tiếng việt',
            },
            remind: {
                remindTitle1: 'にほんご提醒您',
                remindTitle2: 'にほんご離開退稅機前務必取得退稅表單',
                remindTitle3: 'にほんご請準備好您的護照/入臺證、購物發票開始辦理退稅',
                btTitle: 'にほんご開始退稅',
                toSelectDoc: 'selectDoc',
            },
            selectDoc: {
                selectTitle: 'にほんご請選擇本次入境臺灣所使用證照',
                passport: 'にほんご護照',
                permit: 'にほんご許可證',
                toScanPassport: 'scanPassport',
                toScanPermit: 'scanPermit',
            },
            scanPassport: {
                scanPassportTitle: 'にほんご請掃描您的護照',
                scanError: 'にほんご掃描錯誤，請重新操作',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
            },
            scanPermit: {
                scanPermitTitle: 'にほんご請掃描您的入臺證條碼',
                scanError: 'にほんご掃描錯誤，請重新操作',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
            },
            error: {
                errorTitle: 'にほんご請攜帶您的身分資料及發票至服務中心101號櫃台，',
                errorTitle2: 'にほんご將有專人為您服務，謝謝',
                toHomeText: 'にほんご首頁',
            },
            preScanQRcode: {
                preScanQRcodeTitle: 'にほんご準備掃描購物發票QR Code',
                btScanQRcode: 'にほんご開始掃描',
                toScanQR: 'scanQRcode',
            },
            scanQRcode: {
                scanQRcodeTitle1: 'にほんご請掃描您的購物發票',

                scanQRcodeTitle2: '您今日已辦理退稅',
                scanQRcodeTitle4: '元',

                scanQRcodeTitle5: '發票掃描',
                scanQRcodeTitle6: '消費金額',
                scanQRcodeTitle7: '退稅淨額',

                scanQRcodeTitle8: '張',
                scanQRcodeTitle9: '新台幣',
                scanQRcodeTitle10: '新台幣',

                scanQRcodeTitle14: '詳細資訊',
                scanQRcodeTitle15: '確認',

                scanQRError1: 'にほんご非本日發票無法申請退稅，',
                scanQRError2: 'にほんご請掃描下一張發票',
                toDetail: 'detail',
                toSign: 'sign',
            },
            detail: {
                detailTitle1: 'にほんご您已輸入的購物發票',
                detailTitle2: '上下滑動看更多',
                detailTitle3: 'にほんご：',
                detailTitle4: 'に品名/型號：',
                detailTitle5: 'に單價/數量：',
                detailTitle6: 'に含稅金額：',
                btDetail1: '確認，回上一頁',
                btDetail2: '刪除',
                toScanQR: 'scanQRcode',
            },
            sign: {
                signTitle1: 'にほんご請於下方欄位簽名',
                signTitle2: ' にほんご',
                btSign1: '清除簽名',
                btSign2: '確認簽名',
                toSuccess: 'success',
            },
            success: {
                successTitle1: 'にほんご，明細表列印中，請稍後！',
                successTitle2: 'にほんご者請持明細表至服務櫃檯領取退稅款現金。',
                successTitle3: 'にほんご請至出境機場/港口領取您的退稅款，',
                successTitle4: 'にほんご館內市區特約退稅櫃檯。',
                toHomeText: 'にほ首頁',
            },
        },

        //韓文
        4: {
            mainMenu: {
                mainMenuTitle1: "歡迎使用自助退稅服務，請選擇語言",
                mainMenuTitle2: "Welcome to tax refund self-service kiosk.",
                mainMenuTitle3: "Please select language",

                lang01: '中文',
                lang02: 'English',
                lang03: '日本語',
                lang04: '한국어',
                lang05: 'ไทย',
                lang06: 'हिन्दी',
                lang07: 'Español',
                lang08: 'Le français',
                lang09: 'русский',
                lang10: 'Tiếng việt',
            },
            remind: {
                remindTitle1: '한국어提醒您',
                remindTitle2: '한국어離開退稅機前務必取得退稅表單',
                remindTitle3: '한국어請準備好您的護照/入臺證、購物發票開始辦理退稅',
                btTitle: '한국어開始退稅',
                toSelectDoc: 'selectDoc',
            },
            selectDoc: {
                selectTitle: '한국어請選擇本次入境臺灣所使用證照',
                passport: '한국어護照',
                permit: '한국어許可證',
                toScanPassport: 'scanPassport',
                toScanPermit: 'scanPermit',
            },
            scanPassport: {
                scanPassportTitle: '한국어請掃描您的護照',
                scanError: '한국어掃描錯誤，請重新操作',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
            },
            scanPermit: {
                scanPermitTitle: '한국어請掃描您的入臺證條碼',
                scanError: '한국어掃描錯誤，請重新操作',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
            },
            error: {
                errorTitle: '한국어的身分資料及發票至服務中心101號櫃台，',
                errorTitle2: '한국어將有專人為您服務，謝謝',
                toHomeText: '한국어服務首頁',
            },
            preScanQRcode: {
                preScanQRcodeTitle: '한국어準備掃描購物發票QR Code',
                btScanQRcode: '한국어開始掃描',
                toScanQR: 'scanQRcode',
            },
            scanQRcode: {
                scanQRcodeTitle1: '한국어請掃描您的購物發票',

                scanQRcodeTitle2: '한국어您今日已辦理退稅',

                scanQRcodeTitle4: '元',

                scanQRcodeTitle5: '發票掃描',
                scanQRcodeTitle6: '消費金額',
                scanQRcodeTitle7: '退稅淨額',

                scanQRcodeTitle8: '張',
                scanQRcodeTitle9: '新台幣',
                scanQRcodeTitle10: '新台幣',

                scanQRcodeTitle14: '詳細資訊',
                scanQRcodeTitle15: '確認',

                scanQRError1: '한국어非本日發票無法申請退稅，',
                scanQRError2: '請掃描下一張發票',
                toDetail: 'detail',
                toSign: 'sign',
            },
            detail: {
                detailTitle1: '한국어您已輸入的購物發票',
                detailTitle2: '上下滑動看更多',
                detailTitle3: '한국어號碼：',
                detailTitle4: '한品名/型號：',
                detailTitle5: '한單價/數量：',
                detailTitle6: '한含稅金額：',
                btDetail1: '確認，回上一頁',
                btDetail2: '刪除',
                toScanQR: 'scanQRcode',
            },
            sign: {
                signTitle1: '한국어請於下方欄位簽名',
                signTitle2: ' 秒',
                btSign1: '清除簽名',
                btSign2: '確認簽名',
                toSuccess: 'success',
            },
            success: {
                successTitle1: '한국어申請成功，明細表列印中，請稍後！',
                successTitle2: '小額退稅者請持明細表至服務櫃檯領取退稅款現金。',
                successTitle3: '大額退稅請至出境機場/港口領取您的退稅款，',
                successTitle4: '或洽101館內市區特約退稅櫃檯。',
                toHomeText: '한국어服務首頁',
            },
        },

        ///////////////////////////

        5: {
            mainMenu: {
                mainMenuTitle1: "歡迎使用自助退稅服務，請選擇語言",
                mainMenuTitle2: "Welcome to tax refund self-service kiosk.",
                mainMenuTitle3: "Please select language",

                lang01: '中文',
                lang02: 'English',
                lang03: '日本語',
                lang04: '한국어',
                lang05: 'ไทย',
                lang06: 'हिन्दी',
                lang07: 'Español',
                lang08: 'Le français',
                lang09: 'русский',
                lang10: 'Tiếng việt',
            },
            remind: {
                remindTitle1: 'en提醒您',
                remindTitle2: 'en離開退稅機前務必取得退稅表單',
                remindTitle3: 'en請準備好您的護照/入臺證、購物發票開始辦理退稅',
                btTitle: '確認，開始退稅',
                toSelectDoc: 'selectDoc',
            },
            selectDoc: {
                selectTitle: 'Select your ID document used to enter Taiwan during this trip',
                passport: 'Passport',
                permit: 'Exit and Entry Permit',
                toScanPassport: 'scanPassport',
                toScanPermit: 'scanPermit',
            },
            scanPassport: {
                scanPassportTitle: 'Please scan your passport',
                scanError: 'Scan error, please try again',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
            },
            scanPermit: {
                scanPermitTitle: 'Please scan your permit',
                scanError: 'Scan error, please try again',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
            },
            error: {
                errorTitle: 'en請攜帶您的身分資料及發票至服務中心101號櫃台，',
                errorTitle2: 'en將有專人為您服務，謝謝',
                toHomeText: 'en回服務首頁',
            },
            preScanQRcode: {
                preScanQRcodeTitle: 'Prepare to scan QR Code within your invoices',
                btScanQRcode: 'Start scan',
                toScanQR: 'scanQRcode',
            },
            scanQRcode: {
                scanQRcodeTitle1: 'Please scan QR Code within your invoices',

                scanQRcodeTitle2: '您今日已辦理退稅',
                scanQRcodeTitle3: '245',
                scanQRcodeTitle4: '元',

                scanQRcodeTitle5: '發票掃描',
                scanQRcodeTitle6: '消費金額',
                scanQRcodeTitle7: '退稅淨額',

                scanQRcodeTitle8: '張',
                scanQRcodeTitle9: '新台幣',
                scanQRcodeTitle10: '新台幣',
                scanQRcodeTitle11: '1',
                scanQRcodeTitle12: '1,000,000',
                scanQRcodeTitle13: '19,047',

                scanQRcodeTitle14: '詳細資訊',
                scanQRcodeTitle15: '確認',

                scanQRError1: 'en非本日發票無法申請退稅，',
                scanQRError2: 'en請掃描下一張發票',
                toDetail: 'detail',
                toSign: 'sign',
            },
            detail: {
                detailTitle1: 'You have scanned below invoices',
                detailTitle2: '上下滑動看更多',
                detailTitle3: 'en發票號碼：MT 57302841',
                detailTitle4: 'en品名/型號：',
                detailTitle5: 'en單價/數量：',
                detailTitle6: 'en含稅金額：',
                btDetail1: '確認，回上一頁',
                btDetail2: '刪除',
                toScanQR: 'scanQRcode',
            },
            sign: {
                signTitle1: 'Please sign in the below space',
                signTitle2: ' sec.',
                btSign1: '清除簽名',
                btSign2: '確認簽名',
                toSuccess: 'success',
            },
            success: {
                successTitle1: 'en申請成功，明細表列印中，請稍後！',
                successTitle2: 'en小額退稅者請持明細表至服務櫃檯領取退稅款現金。',
                successTitle3: 'en大額退稅請至出境機場/港口領取您的退稅款，',
                successTitle4: 'en或洽101館內市區特約退稅櫃檯。',
                toHomeText: '한국어服務首頁',
            },
        },

        6: {
            mainMenu: {
                mainMenuTitle1: "歡迎使用自助退稅服務，請選擇語言",
                mainMenuTitle2: "Welcome to tax refund self-service kiosk.",
                mainMenuTitle3: "Please select language",

                lang01: '中文',
                lang02: 'English',
                lang03: '日本語',
                lang04: '한국어',
                lang05: 'ไทย',
                lang06: 'हिन्दी',
                lang07: 'Español',
                lang08: 'Le français',
                lang09: 'русский',
                lang10: 'Tiếng việt',
            },
            remind: {
                remindTitle1: '提醒您',
                remindTitle2: '離開退稅機前務必取得退稅表單',
                remindTitle3: '請準備好您的護照/入臺證、購物發票開始辦理退稅',
                btTitle: '確認，開始退稅',
                toSelectDoc: 'selectDoc',
            },
            selectDoc: {
                selectTitle: '請選擇本次入境臺灣所使用證照',
                passport: '護照',
                permit: '入出境許可證',
                toScanPassport: 'scanPassport',
                toScanPermit: 'scanPermit',
            },
            scanPassport: {
                scanPassportTitle: '請掃描您的護照',
                scanError: '掃描錯誤，請重新操作',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
            },
            scanPermit: {
                scanPermitTitle: '請掃描您的入臺證條碼',
                scanError: '掃描錯誤，請重新操作',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
            },
            error: {
                errorTitle: '請攜帶您的身分資料及發票至服務中心101號櫃台，',
                errorTitle2: '將有專人為您服務，謝謝',
                toHomeText: '回服務首頁',
            },
            preScanQRcode: {
                preScanQRcodeTitle: '準備掃描購物發票QR Code',
                btScanQRcode: '開始掃描',
                toScanQR: 'scanQRcode',
            },
            scanQRcode: {
                scanQRcodeTitle: '請掃描您的購物發票',

                scanQRcodeTitle2: '您今日已辦理退稅',
                scanQRcodeTitle3: '245',
                scanQRcodeTitle4: '元',

                scanQRcodeTitle5: '發票掃描',
                scanQRcodeTitle6: '消費金額',
                scanQRcodeTitle7: '退稅淨額',

                scanQRcodeTitle8: '張',
                scanQRcodeTitle9: '新台幣',
                scanQRcodeTitle10: '新台幣',
                scanQRcodeTitle11: '1',
                scanQRcodeTitle12: '1,000,000',
                scanQRcodeTitle13: '19,047',

                scanQRcodeTitle14: '詳細資訊',
                scanQRcodeTitle15: '確認',

                scanQRError1: '非本日發票無法申請退稅，',
                scanQRError2: '請掃描下一張發票',
                toDetail: 'detail',
                toSign: 'sign',
            },
            detail: {
                detailTitle1: '您已輸入的購物發票',
                detailTitle2: '上下滑動看更多',
                detailTitle3: '發票號碼：MT 57302841',
                detailTitle4: '品名/型號：',
                detailTitle5: '單價/數量：',
                detailTitle6: '含稅金額：',
                btDetail1: '確認，回上一頁',
                btDetail2: '刪除',
                toScanQR: 'scanQRcode',
            },
            sign: {
                signTitle1: '請於下方欄位簽名',
                signTitle2: '59 秒',
                btSign1: '清除簽名',
                btSign2: '確認簽名',
                toSuccess: 'success',
            },
            success: {
                successTitle1: '申請成功，明細表列印中，請稍後！',
                successTitle2: '小額退稅者請持明細表至服務櫃檯領取退稅款現金。',
                successTitle3: '大額退稅請至出境機場/港口領取您的退稅款，',
                successTitle4: '或洽101館內市區特約退稅櫃檯。',
                toHomeText: '한국어服務首頁',
            },
        },

        7: {
            mainMenu: {
                mainMenuTitle1: "歡迎使用自助退稅服務，請選擇語言",
                mainMenuTitle2: "Welcome to tax refund self-service kiosk.",
                mainMenuTitle3: "Please select language",

                lang01: '中文',
                lang02: 'English',
                lang03: '日本語',
                lang04: '한국어',
                lang05: 'ไทย',
                lang06: 'हिन्दी',
                lang07: 'Español',
                lang08: 'Le français',
                lang09: 'русский',
                lang10: 'Tiếng việt',
            },
            remind: {
                remindTitle1: 'にほんご提醒您',
                remindTitle2: 'にほんご離開退稅機前務必取得退稅表單',
                remindTitle3: 'にほんご請準備好您的護照/入臺證、購物發票開始辦理退稅',
                btTitle: 'にほんご開始退稅',
                toSelectDoc: 'selectDoc',
            },
            selectDoc: {
                selectTitle: 'にほんご請選擇本次入境臺灣所使用證照',
                passport: 'にほんご護照',
                permit: 'にほんご許可證',
                toScanPassport: 'scanPassport',
                toScanPermit: 'scanPermit',
            },
            scanPassport: {
                scanPassportTitle: 'にほんご請掃描您的護照',
                scanError: 'にほんご掃描錯誤，請重新操作',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
            },
            scanPermit: {
                scanPermitTitle: 'にほんご請掃描您的入臺證條碼',
                scanError: 'にほんご掃描錯誤，請重新操作',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
            },
            error: {
                errorTitle: 'にほんご請攜帶您的身分資料及發票至服務中心101號櫃台，',
                errorTitle2: 'にほんご將有專人為您服務，謝謝',
                toHomeText: 'にほんご首頁',
            },
            preScanQRcode: {
                preScanQRcodeTitle: 'にほんご準備掃描購物發票QR Code',
                btScanQRcode: 'にほんご開始掃描',
                toScanQR: 'scanQRcode',
            },
            scanQRcode: {
                scanQRcodeTitle: 'にほんご請掃描您的購物發票',

                scanQRcodeTitle2: '您今日已辦理退稅',
                scanQRcodeTitle3: '245',
                scanQRcodeTitle4: '元',

                scanQRcodeTitle5: '發票掃描',
                scanQRcodeTitle6: '消費金額',
                scanQRcodeTitle7: '退稅淨額',

                scanQRcodeTitle8: '張',
                scanQRcodeTitle9: '新台幣',
                scanQRcodeTitle10: '新台幣',
                scanQRcodeTitle11: '1',
                scanQRcodeTitle12: '1,000,000',
                scanQRcodeTitle13: '19,047',

                scanQRcodeTitle14: '詳細資訊',
                scanQRcodeTitle15: '確認',

                scanQRError1: 'にほんご非本日發票無法申請退稅，',
                scanQRError2: 'にほんご請掃描下一張發票',
                toDetail: 'detail',
                toSign: 'sign',
            },
            detail: {
                detailTitle1: 'にほんご您已輸入的購物發票',
                detailTitle2: '上下滑動看更多',
                detailTitle3: 'にほんご：MT 57302841',
                detailTitle4: 'にほんご品名/型號：',
                detailTitle5: 'にほんご單價/數量：',
                detailTitle6: 'にほんご含稅金額：',
                btDetail1: '確認，回上一頁',
                btDetail2: '刪除',
                toScanQR: 'scanQRcode',
            },
            sign: {
                signTitle1: 'にほんご請於下方欄位簽名',
                signTitle2: ' にほんご',
                btSign1: '清除簽名',
                btSign2: '確認簽名',
                toSuccess: 'success',
            },
            success: {
                successTitle1: 'にほんご，明細表列印中，請稍後！',
                successTitle2: 'にほんご者請持明細表至服務櫃檯領取退稅款現金。',
                successTitle3: 'にほんご請至出境機場/港口領取您的退稅款，',
                successTitle4: 'にほんご館內市區特約退稅櫃檯。',
                toHomeText: '한국어服務首頁',
            },
        },

        8: {
            mainMenu: {
                mainMenuTitle1: "歡迎使用自助退稅服務，請選擇語言",
                mainMenuTitle2: "Welcome to tax refund self-service kiosk.",
                mainMenuTitle3: "Please select language",

                lang01: '中文',
                lang02: 'English',
                lang03: '日本語',
                lang04: '한국어',
                lang05: 'ไทย',
                lang06: 'हिन्दी',
                lang07: 'Español',
                lang08: 'Le français',
                lang09: 'русский',
                lang10: 'Tiếng việt',
            },
            remind: {
                remindTitle1: '한국어提醒您',
                remindTitle2: '한국어離開退稅機前務必取得退稅表單',
                remindTitle3: '한국어請準備好您的護照/入臺證、購物發票開始辦理退稅',
                btTitle: '한국어開始退稅',
                toSelectDoc: 'selectDoc',
            },
            selectDoc: {
                selectTitle: '한국어請選擇本次入境臺灣所使用證照',
                passport: '한국어護照',
                permit: '한국어許可證',
                toScanPassport: 'scanPassport',
                toScanPermit: 'scanPermit',
            },
            scanPassport: {
                scanPassportTitle: '한국어請掃描您的護照',
                scanError: '한국어掃描錯誤，請重新操作',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
            },
            scanPermit: {
                scanPermitTitle: '한국어請掃描您的入臺證條碼',
                scanError: '한국어掃描錯誤，請重新操作',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
            },
            error: {
                errorTitle: '한국어的身分資料及發票至服務中心101號櫃台，',
                errorTitle2: '한국어將有專人為您服務，謝謝',
                toHomeText: '한국어服務首頁',
            },
            preScanQRcode: {
                preScanQRcodeTitle: '한국어準備掃描購物發票QR Code',
                btScanQRcode: '한국어開始掃描',
                toScanQR: 'scanQRcode',
            },
            scanQRcode: {
                scanQRcodeTitle: '한국어請掃描您的購物發票',

                scanQRcodeTitle2: '한국어您今日已辦理退稅',
                scanQRcodeTitle3: '245',
                scanQRcodeTitle4: '元',

                scanQRcodeTitle5: '發票掃描',
                scanQRcodeTitle6: '消費金額',
                scanQRcodeTitle7: '退稅淨額',

                scanQRcodeTitle8: '張',
                scanQRcodeTitle9: '新台幣',
                scanQRcodeTitle10: '新台幣',
                scanQRcodeTitle11: '1',
                scanQRcodeTitle12: '1,000,000',
                scanQRcodeTitle13: '19,047',

                scanQRcodeTitle14: '詳細資訊',
                scanQRcodeTitle15: '確認',

                scanQRError1: '한국어非本日發票無法申請退稅，',
                scanQRError2: '請掃描下一張發票',
                toDetail: 'detail',
                toSign: 'sign',
            },
            detail: {
                detailTitle1: '한국어您已輸入的購物發票',
                detailTitle2: '上下滑動看更多',
                detailTitle3: '한국어發票號碼：MT 57302841',
                detailTitle4: '한국어品名/型號：',
                detailTitle5: '한국어單價/數量：',
                detailTitle6: '한국어含稅金額：',
                btDetail1: '確認，回上一頁',
                btDetail2: '刪除',
                toScanQR: 'scanQRcode',
            },
            sign: {
                signTitle1: '한국어請於下方欄位簽名',
                signTitle2: ' 秒',
                btSign1: '清除簽名',
                btSign2: '確認簽名',
                toSuccess: 'success',
            },
            success: {
                successTitle1: '한국어申請成功，明細表列印中，請稍後！',
                successTitle2: '小額退稅者請持明細表至服務櫃檯領取退稅款現金。',
                successTitle3: '大額退稅請至出境機場/港口領取您的退稅款，',
                successTitle4: '或洽101館內市區特約退稅櫃檯。',
                toHomeText: '한국어服務首頁',
            },
        },

        9: {
            mainMenu: {
                mainMenuTitle1: "歡迎使用自助退稅服務，請選擇語言",
                mainMenuTitle2: "Welcome to tax refund self-service kiosk.",
                mainMenuTitle3: "Please select language",

                lang01: '中文',
                lang02: 'English',
                lang03: '日本語',
                lang04: '한국어',
                lang05: 'ไทย',
                lang06: 'हिन्दी',
                lang07: 'Español',
                lang08: 'Le français',
                lang09: 'русский',
                lang10: 'Tiếng việt',
            },
            remind: {
                remindTitle1: 'にほんご提醒您',
                remindTitle2: 'にほんご離開退稅機前務必取得退稅表單',
                remindTitle3: 'にほんご請準備好您的護照/入臺證、購物發票開始辦理退稅',
                btTitle: 'にほんご開始退稅',
                toSelectDoc: 'selectDoc',
            },
            selectDoc: {
                selectTitle: 'にほんご請選擇本次入境臺灣所使用證照',
                passport: 'にほんご護照',
                permit: 'にほんご許可證',
                toScanPassport: 'scanPassport',
                toScanPermit: 'scanPermit',
            },
            scanPassport: {
                scanPassportTitle: 'にほんご請掃描您的護照',
                scanError: 'にほんご掃描錯誤，請重新操作',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
            },
            scanPermit: {
                scanPermitTitle: 'にほんご請掃描您的入臺證條碼',
                scanError: 'にほんご掃描錯誤，請重新操作',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
            },
            error: {
                errorTitle: 'にほんご請攜帶您的身分資料及發票至服務中心101號櫃台，',
                errorTitle2: 'にほんご將有專人為您服務，謝謝',
                toHomeText: 'にほんご首頁',
            },
            preScanQRcode: {
                preScanQRcodeTitle: 'にほんご準備掃描購物發票QR Code',
                btScanQRcode: 'にほんご開始掃描',
                toScanQR: 'scanQRcode',
            },
            scanQRcode: {
                scanQRcodeTitle: 'にほんご請掃描您的購物發票',

                scanQRcodeTitle2: '您今日已辦理退稅',
                scanQRcodeTitle3: '245',
                scanQRcodeTitle4: '元',

                scanQRcodeTitle5: '發票掃描',
                scanQRcodeTitle6: '消費金額',
                scanQRcodeTitle7: '退稅淨額',

                scanQRcodeTitle8: '張',
                scanQRcodeTitle9: '新台幣',
                scanQRcodeTitle10: '新台幣',
                scanQRcodeTitle11: '1',
                scanQRcodeTitle12: '1,000,000',
                scanQRcodeTitle13: '19,047',

                scanQRcodeTitle14: '詳細資訊',
                scanQRcodeTitle15: '確認',

                scanQRError1: 'にほんご非本日發票無法申請退稅，',
                scanQRError2: 'にほんご請掃描下一張發票',
                toDetail: 'detail',
                toSign: 'sign',
            },
            detail: {
                detailTitle1: 'にほんご您已輸入的購物發票',
                detailTitle2: '上下滑動看更多',
                detailTitle3: 'にほんご：MT 57302841',
                detailTitle4: 'にほんご品名/型號：',
                detailTitle5: 'にほんご單價/數量：',
                detailTitle6: 'にほんご含稅金額：',
                btDetail1: '確認，回上一頁',
                btDetail2: '刪除',
                toScanQR: 'scanQRcode',
            },
            sign: {
                signTitle1: 'にほんご請於下方欄位簽名',
                signTitle2: ' にほんご',
                btSign1: '清除簽名',
                btSign2: '確認簽名',
                toSuccess: 'success',
            },
            success: {
                successTitle1: 'にほんご，明細表列印中，請稍後！',
                successTitle2: 'にほんご者請持明細表至服務櫃檯領取退稅款現金。',
                successTitle3: 'にほんご請至出境機場/港口領取您的退稅款，',
                successTitle4: 'にほんご館內市區特約退稅櫃檯。',
                toHomeText: '한국어服務首頁',
            },
        },

        10: {
            mainMenu: {
                mainMenuTitle1: "歡迎使用自助退稅服務，請選擇語言",
                mainMenuTitle2: "Welcome to tax refund self-service kiosk.",
                mainMenuTitle3: "Please select language",

                lang01: '中文',
                lang02: 'English',
                lang03: '日本語',
                lang04: '한국어',
                lang05: 'ไทย',
                lang06: 'हिन्दी',
                lang07: 'Español',
                lang08: 'Le français',
                lang09: 'русский',
                lang10: 'Tiếng việt',
            },
            remind: {
                remindTitle1: '한국어提醒您',
                remindTitle2: '한국어離開退稅機前務必取得退稅表單',
                remindTitle3: '한국어請準備好您的護照/入臺證、購物發票開始辦理退稅',
                btTitle: '한국어開始退稅',
                toSelectDoc: 'selectDoc',
            },
            selectDoc: {
                selectTitle: '한국어請選擇本次入境臺灣所使用證照',
                passport: '한국어護照',
                permit: '한국어許可證',
                toScanPassport: 'scanPassport',
                toScanPermit: 'scanPermit',
            },
            scanPassport: {
                scanPassportTitle: '한국어請掃描您的護照',
                scanError: '한국어掃描錯誤，請重新操作',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
            },
            scanPermit: {
                scanPermitTitle: '한국어請掃描您的入臺證條碼',
                scanError: '한국어掃描錯誤，請重新操作',
                toError: 'error',
                toPreScanQR: 'preScanQRcode',
            },
            error: {
                errorTitle: '한국어的身分資料及發票至服務中心101號櫃台，',
                errorTitle2: '한국어將有專人為您服務，謝謝',
                toHomeText: '한국어服務首頁',
            },
            preScanQRcode: {
                preScanQRcodeTitle: '한국어準備掃描購物發票QR Code',
                btScanQRcode: '한국어開始掃描',
                toScanQR: 'scanQRcode',
            },
            scanQRcode: {
                scanQRcodeTitle: '한국어請掃描您的購物發票',

                scanQRcodeTitle2: '한국어您今日已辦理退稅',
                scanQRcodeTitle3: '245',
                scanQRcodeTitle4: '元',

                scanQRcodeTitle5: '發票掃描',
                scanQRcodeTitle6: '消費金額',
                scanQRcodeTitle7: '退稅淨額',

                scanQRcodeTitle8: '張',
                scanQRcodeTitle9: '新台幣',
                scanQRcodeTitle10: '新台幣',
                scanQRcodeTitle11: '1',
                scanQRcodeTitle12: '1,000,000',
                scanQRcodeTitle13: '19,047',

                scanQRcodeTitle14: '詳細資訊',
                scanQRcodeTitle15: '確認',

                scanQRError1: '한국어非本日發票無法申請退稅，',
                scanQRError2: '請掃描下一張發票',
                toDetail: 'detail',
                toSign: 'sign',
            },
            detail: {
                detailTitle1: '한국어您已輸入的購物發票',
                detailTitle2: '上下滑動看更多',
                detailTitle3: '한국어發票號碼：MT 57302841',
                detailTitle4: '한국어品名/型號：',
                detailTitle5: '한국어單價/數量：',
                detailTitle6: '한국어含稅金額：',
                btDetail1: '確認，回上一頁',
                btDetail2: '刪除',
                toScanQR: 'scanQRcode',
            },
            sign: {
                signTitle1: '한국어請於下方欄位簽名',
                signTitle2: ' 秒',
                btSign1: '清除簽名',
                btSign2: '確認簽名',
                toSuccess: 'success',
            },
            success: {
                successTitle1: '한국어申請成功，明細表列印中，請稍後！',
                successTitle2: '小額退稅者請持明細表至服務櫃檯領取退稅款現金。',
                successTitle3: '大額退稅請至出境機場/港口領取您的退稅款，',
                successTitle4: '或洽101館內市區特約退稅櫃檯。',
                toHomeText: '한국어服務首頁',
            },
        },
    };

    kiosk.cultureMap = {
        'en-US': kiosk.enum.culture.ENUS,
        'zh-TW': kiosk.enum.culture.ZHTW,
        'ja-JP': kiosk.enum.culture.JAJP,
        'ko-KR': kiosk.enum.culture.KOKR,
        'zh-CN': kiosk.enum.culture.ZHCN,
        1: 'en-US',
        2: 'zh-TW',
        3: 'ja-rJP',
        4: 'ko-rKR',
        5: 'zh-rCN',
    };
    kiosk.cultureArry = [1, 2, 3, 4, 5];

    kiosk.secondMideaType = 'Video';
})();
